---
- name: Create VM from Template
  vmware_guest:
      validate_certs: false
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_admin }}"
      password: "{{ vcenter_pass }}"
      cluster: "{{ vcenter_cluster }}"
      datacenter: "{{ vcenter_datacenter }}"
      name: "{{ guest_hostname }}"
      folder: "{{ vm_folder }}"
      template: "{{ vm_template }}"
      datastore: "{{ datastore }}"
      networks:
      - name: "{{ vm_network }}"
        ip: "{{ guest_ip }}"
        netmask: "{{ guest_netmask }}"
        gateway: "{{ guest_gateway }}"
      hardware:
        num_cpus: "{{ guest_vcpu }}"
        memory_mb: "{{ guest_ram }}"
      customization:
        hostname: "{{ guest_hostname }}"
        password: "{{ labadmin_pass }}"
      wait_for_customization: True
      state: powerdon
  delegate_to: localhost
  register: newvm
- name: Wait until connection to VM
  wait_for_connection:
    delay: 5
    timeout: 300
- name: Gather facts for the first time
  setup:
