---
- name: Update resolv.conf
  hosts: ipaclients
  become: true

  tasks:
    - name: Remove existing nameservers
      lineinfile:
        path: /etc/resolv.conf
        state: absent
        regexp: '^nameserver'
      
    - name: Add new nameservers
      blockinfile:
        path: /etc/resolv.conf
        block: |
          nameserver 192.168.0.10
          nameserver 8.8.8.8

- name: Configure IPA Client
  hosts: ipaclients
  become: true
  vars_files:
  - ipa-secrets.yml

  roles:
    - role: ipaclient
      state: present

  handlers:
    - name: Restart SSSD
      systemd:
        name: sssd
        state: restarted
