---
- name: Create App Drive on sdb
  hosts: localhost
  become: true

  tasks:
    - name: Check if VG exists
      lvol_info:
        vg: vg_app
      register: vg_check

    - name: Check if LV exists
      lvol_info:
        vg: vg_app
        lv: lv_app
      register: lv_check

    - name: Create PV and VG named vg_app
      lvg:
        pvs: /dev/sdb
        vg: vg_app
        state: present
      when: vg_check.vg_info is not defined
      run_once: true

    - name: Create Logical Volume (LV) named lv_app
      lvol:
        vg: vg_app
        lv: lv_app
        size: 100%FREE
        state: present
      when: lv_check.lv_info is not defined
      run_once: true

    - name: Format LV with XFS filesystem
      filesystem:
        fstype: xfs
        dev: /dev/vg_app/lv_app
      when: lv_check.lv_info is not defined
      run_once: true

    - name: Create /app directory
      file:
        path: /app
        state: directory
        mode: '0755'

    - name: Mount LV to /app
      mount:
        path: /app
        src: /dev/vg_app/lv_app
        fstype: xfs
        state: mounted

    - name: Update /etc/fstab
      lineinfile:
        path: /etc/fstab
        regexp: "^.*\\s+/app\\s+.*$"
        line: "/dev/vg_app/lv_app    /app    xfs    defaults    0 0"
      run_once: true
